Traceback (most recent call last):
  File "/home-mscluster/nranchod/honours-research/ga.py", line 119, in <module>
    bot = GeneticAlgorithmBot()
  File "/home-mscluster/nranchod/honours-research/ga.py", line 18, in __init__
    self.engine = chess.engine.SimpleEngine.popen_uci("stockfish/stockfish")
  File "/home-mscluster/nranchod/miniconda3/envs/research/lib/python3.10/site-packages/chess/engine.py", line 3054, in popen_uci
    return cls.popen(UciProtocol, command, timeout=timeout, debug=debug, setpgrp=setpgrp, **popen_args)
  File "/home-mscluster/nranchod/miniconda3/envs/research/lib/python3.10/site-packages/chess/engine.py", line 3046, in popen
    return run_in_background(background, name=f"{cls.__name__} (command={command!r})", debug=debug)
  File "/home-mscluster/nranchod/miniconda3/envs/research/lib/python3.10/site-packages/chess/engine.py", line 201, in run_in_background
    return future.result()
  File "/home-mscluster/nranchod/miniconda3/envs/research/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home-mscluster/nranchod/miniconda3/envs/research/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home-mscluster/nranchod/miniconda3/envs/research/lib/python3.10/site-packages/chess/engine.py", line 195, in background
    asyncio.run(coroutine(future))
  File "/home-mscluster/nranchod/miniconda3/envs/research/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home-mscluster/nranchod/miniconda3/envs/research/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home-mscluster/nranchod/miniconda3/envs/research/lib/python3.10/site-packages/chess/engine.py", line 3038, in background
    await asyncio.wait_for(protocol.initialize(), timeout)
  File "/home-mscluster/nranchod/miniconda3/envs/research/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/home-mscluster/nranchod/miniconda3/envs/research/lib/python3.10/site-packages/chess/engine.py", line 1510, in initialize
    return await self.communicate(UciInitializeCommand)
  File "/home-mscluster/nranchod/miniconda3/envs/research/lib/python3.10/site-packages/chess/engine.py", line 1133, in communicate
    return await command.result
chess.engine.EngineTerminatedError: engine process died unexpectedly (exit code: -4, binary not compatible with cpu?)
